### ISSUE TITLE
Found a bug Cannot read property 'clearRect' of null 

### ISSUE THREAD

**Issue by ahmedrazaa** [vutran6853/vue3-chartjs#19]
here is error details.to reproduce this error I used a drop down every time I change the dropdown data its throw this error

Chart.js?d6c6:2744 
       Uncaught TypeError: Cannot read properties of null (reading 'clearRect')
    at Object.clear (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:2743:13)
    at Chart.clear (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:9403:20)
    at Chart.draw (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:9820:6)
    at Chart.render (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:9798:12)
    at Object.callback (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:2207:14)
    at Object.advance (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:3543:14)
    at Object.startDigest (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:3516:6)
    at eval (webpack-internal:///./node_modules/vue3-chart-v2/node_modules/chart.js/dist/Chart.js:3505:8)

**Comment by sarahmeh** [comment]
Hi, were you able to fix this issue? I'm also experiencing it on my chart.
